 export const bookList = [
  {
    image: "./assets/images/Product images/ark.jpg",
    title: "Тріумфальна арка",
    author: "Еріх Марія Ремарк",
    price: 100,
    quantity: 90,
    inCart: 0,
    id: 1,
  },
  {
    image: "./assets/images/Product images/cafe.jpg",
    title: "Кафе на краю світу",
    author: "Джон П. Стерлекі",
    price: 269,
    quantity: 10,
    inCart: 0,
    id: 2,
  },
  {
    image: "./assets/images/Product images/city.jpg",
    title: "Місто дівчат",
    author: "Елізабет Гілберт",
    price: 178,
    quantity: 3,
    inCart: 0,
    id: 3,
  },
  {
    image: "./assets/images/Product images/gal.jpg",
    title: "Чайка на ім`я Джонатан Лівінгстон",
    author: " Річард Бах",
    price: 118,
    quantity: 2,
    inCart: 0,
    id: 4,
  },
  {
    image: "./assets/images/Product images/god.jpg",
    title: "Бог завжди подорожує інкогніто",
    author: "Лоран Гунель",
    price: 400,
    quantity: 6,
    inCart: 0,
    id: 5,
  },
  {
    image: "./assets/images/Product images/head.jpg",
    title: "#Галябезголови",
    author: "Люко Дашвар",
    price: 279,
    quantity: 3,
    inCart: 0,
    id: 6,
  },
  {
    image: "./assets/images/Product images/master.jpg",
    title: "Володар мух",
    author: "Вільям Ґолдінґ",
    price: 157,
    quantity: 9,
    inCart: 0,
    id: 7,
  },
  {
    image: "./assets/images/Product images/one.jpg",
    title: "The one",
    author: "Джон Маррс",
    price: 240,
    quantity: 9,
    inCart: 0,
    id: 8,
  },
  {
    image: "./assets/images/Product images/parfumer.jpg",
    title: "Парфюмер",
    author: "Патрік Зюскінд",
    price: 170,
    quantity: 9,
    inCart: 0,
    id: 9,
  },
  {
    image: "./assets/images/Product images/patient.jpg",
    title: "Безмовний паціент",
    author: "Алекс Міхаелідес",
    price: 160,
    quantity: 20,
    inCart: 0,
    id: 10,
  },
  {
    image: "./assets/images/Product images/people.jpg",
    title: "Тревожные люди",
    author: "Фредрік Бакман",
    price: 65,
    quantity: 11,
    inCart: 0,
    id: 11,
  },
  {
    image: "./assets/images/Product images/Tiffani.jpg",
    title: "Завтрак у Тиффани",
    author: "Трумен Капоте",
    price: 128,
    quantity: 9,
    inCart: 0,
    id: 12,
  },
  {
    image: "./assets/images/Product images/trans.jpg",
    title: "Transhumanism Inc.",
    author: "Віктор  Пелевін",
    price: 267,

    quantity: 9,
    inCart: 0,
    id: 13,
  },
  {
    image: "./assets/images/Product images/wait.png",
    title: "Чекай удома, коли повернуся",
    author: "Ельчін Сафарлі",
    price: 170,
    quantity: 15,
    inCart: 0,
    id: 14,
  },
];

