export const bookList = [
  {
    image: "./assets/images/Product images/ark.jpg",
    title: "Arch of Triumph",
    annotation: "",
    language: "german",
    author: "Erich Paul Remark",
    price: 100,
    quantity: 90,
    inCart: 0,
    ratings: 2,
    id: 1,
  },
  {
    image: "./assets/images/Product images/cafe.jpg",
    title: "The Cafe on the Edge of the World",
    annotation: "",
    language: "english",
    author: "John Strelecky",
    price: 269,
    quantity: 10,
    inCart: 0,
    ratings: 4,
    id: 2,
  },
  {
    image: "./assets/images/Product images/city.jpg",
    title: "City of Girls",
    annotation: "",
    language: "english",
    author: "Elizabeth Gilbert",
    price: 178,
    quantity: 3,
    inCart: 0,
    ratings: 3,
    id: 3,
  },
  {
    image: "./assets/images/Product images/gal.jpg",
    title: "Jonathan Livingston Seagull",
    annotation: "",
    language: "english",
    author: "Richard David Bach",
    price: 118,
    quantity: 2,
    inCart: 0,
    ratings: 6,
    id: 4,
  },
  {
    image: "./assets/images/Product images/god.jpg",
    title: "Les dieux voyagent toujours incognito",
    annotation: `Imaginez : Un homme vous sauve la vie, en échange de votre engagement de faire tout ce qu'il vous demande... pour votre bien. Le dos au mur, vous acceptez et vous vous retrouvez embarqué dans une incroyable situation où tout semble vous échapper. Vous n'êtes plus le maître de votre vie et pourtant... à bien des égards, elle est plus excitante qu'auparavant !
    Mais peu à peu, le doute s'installe en vous : quelles sont les intentions réelles de cet homme qui s'est immiscé dans votre existence ? Qui est-il vraiment? Et qui sont ces personnages énigmatiques dans son entourage? Les découvertes que vous faites n'ont rien pour vous rassurer.
    Cette histoire, qui nous plonge dans l'atmosphère envoûtante d'un été parisien, ouvre la voie de la plus belle des réflexions sur nous-mêmes: qu'est-ce qui peut nous permettre de dépasser nos inhibitions, nos peurs et nos conditionnements, pour sortir du chemin tout tracé de notre vie lorsque celle-ci ne nous apporte pas pleinement satisfaction ?`,
    language: "french",
    author: "Laurent Gounelle",
    price: 400,
    quantity: 6,
    inCart: 0,
    ratings: 3,
    id: 5,
  },
  {
    image: "./assets/images/Product images/head.jpg",
    title: "#Галябезголови",
    annotation:
      "Благими намірами вимощений шлях до пекла. Галя сповна відчула сенс цього вислову. Її життя перевернулося лише через те, що вона прагнула допомогти іншій людині. Дівчина втратила все: роботу, чоловіка, друзів, віру в людей. Та що, як усе найбільш значуще і неймовірне починає відбуватися з нами саме тоді, коми ми намагаємося видряпатися з пекла? Це непросто, бо людина по-справжньому втрачає голову лише від двох речей: від страху і від кохання. Однак що робити, коли тебе одночасно накривають і страх, і кохання?",
    language: "ukrainian",
    author: "Люко Дашвар",
    price: 279,
    quantity: 3,
    inCart: 0,
    ratings: 4,
    id: 6,
  },
  {
    image: "./assets/images/Product images/master.jpg",
    title: "Lord of the Flies",
    annotation:
      "When a plane crashes on a remote island, a small group of schoolboys are the sole survivors. From the prophetic Simon and virtuous Ralph to the lovable Piggy and brutish Jack, each of the boys attempts to establish control as the reality- and brutal savagery-of their situation sets in. A teacher himself, Golding clearly understood how to interest children with a gripping story and strong, sympathetic characters. the novel serves as a catalyst for thought-provoking discussion and analysis of universal issues, not only concerning the capabilities of humans for good and evil and the fragility of moral inhibition, but beyond.",
    language: "english",
    author: "William Golding",
    price: 157,
    quantity: 9,
    inCart: 0,
    ratings: 4,
    id: 7,
  },
  {
    image: "./assets/images/Product images/one.jpg",
    title: "The one",
    annotation:
      "A simple DNA test is all it takes. Just a quick mouth swab and soon you’ll be matched with your perfect partner—the one you’re genetically made for. That’s the promise made by Match Your DNA. A decade ago, the company announced that they had found the gene that pairs each of us with our soul mate. Since then, millions of people around the world have been matched. But the discovery has its downsides: test results have led to the breakup of countless relationships and upended the traditional ideas of dating, romance and love.",
    language: "english",
    author: "John Marrs",
    price: 240,
    quantity: 9,
    inCart: 0,
    ratings: 3,
    id: 8,
  },
  {
    image: "./assets/images/Product images/parfumer.jpg",
    title: "Das Parfum",
    annotation:
      "An acclaimed bestseller and international sensation, Patrick Suskind's classic novel provokes a terrifying examination of what happens when one man's indulgence in his greatest passion—his sense of smell—leads to murder.",
    language: "german",
    author: "Patrick Suskind",
    price: 170,
    quantity: 9,
    inCart: 0,
    ratings: 4,
    id: 9,
  },
  {
    image: "./assets/images/Product images/patient.jpg",
    title: "The Silent Patient ",
    annotation:
      "Alicia Berenson’s life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house with big windows overlooking a park in one of London’s most desirable areas. One evening her husband Gabriel returns home late from a fashion shoot, and Alicia shoots him five times in the face, and then never speaks another word.",
    language: "english",
    author: "Alex Michaelides",
    price: 160,
    quantity: 20,
    inCart: 0,
    ratings: 4,
    id: 10,
  },
  {
    image: "./assets/images/Product images/people.jpg",
    title: "Folk med ångest",
    annotation:
      "A poignant, charming novel about a crime that never took place, a would-be bank robber who disappears into thin air, and eight extremely anxious strangers who find they have more in common than they ever imagined",
    language: "swedish",
    author: "Fredrik Backman",
    price: 65,
    quantity: 11,
    inCart: 0,
    ratings: 4,
    id: 11,
  },
  {
    image: "./assets/images/Product images/Tiffani.jpg",
    title: "	Breakfast at Tiffany's",
    annotation:
      "Holly Golightly knows that nothing bad can ever happen to you at Tiffany's. In this seductive, wistful masterpiece, Capote created a woman whose name has entered the American idiom and whose style is a part of the literary landscape—her poignancy, wit, and naïveté continue to charm.",
    language: "english",
    author: "Truman Capote",
    price: 128,
    quantity: 9,
    inCart: 0,
    ratings: 3,
    id: 12,
  },
  {
    image: "./assets/images/Product images/trans.jpg",
    title: "Transhumanism Inc.",
    annotation:
      "В будущем богатые люди смогут отделить свой мозг от старящегося тела - и станут жить почти вечно в особом “баночном” измерении. Туда уйдут вожди, мировые олигархи и архитекторы миропорядка. Там будет возможно все. Но в банку пустят не каждого. На земле останется зеленая посткарбоновая цивилизация, уменьшенная до размеров обслуживающего персонала, и слуги-биороботы.",

    language: "russian",
    author: "Виктор  Пелевин",
    price: 267,

    quantity: 9,
    inCart: 0,
    ratings: 1,
    id: 13,
  },
  {
    image: "./assets/images/Product images/wait.png",
    title: "Когда я вернусь, будь дома",
    annotation:
      "Теперь я отчетливее ощущаю вечность жизни. Никто не умрет, и те, кто любил друг друга в одной жизни, непременно встретятся после. Тело, имя, национальность – все будет иным, но нас притянет магнитом: любовь связывает навсегда. А пока что я проживаю жизнь – люблю и, бывает, устаю от любви. Запоминаю мгновения, бережно храню в себе эту память, чтобы завтра или в следующей жизни обо всем написать.",
    language: "russian",
    author: "Elchin Safarli",
    price: 170,
    quantity: 15,
    inCart: 0,
    ratings: 3,
    id: 14,
  },
];
